name: Terraform plan
on:
  workflow_dispatch:
permissions:
  contents: read
  id-token: write
concurrency:
  group: terraform-plan
  cancel-in-progress: false
jobs:
  plan:
    runs-on: ubuntu-latest
    environment: prod
    env:
      TF_VAR_site_bucket_name: ${{ vars.SITE_BUCKET_NAME }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: '${{ github.sha }}'
      - uses: hashicorp/setup-terraform@v3
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_PLAN_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
      - run: terraform -chdir=infra init -backend-config="bucket=${{ vars.STATE_BUCKET_NAME }}" -backend-config="region=${{ vars.AWS_REGION }}"
      - run: terraform -chdir=infra plan
